# Importing requests libraries

In [21]:
import pandas as pd
import numpy as np

# 1. Basic Data Inspection

In [2]:
df_raw = pd.read_csv('..\\..\\data\\raw\\anime_catalog.csv')
df = df_raw.copy()
df.sample(5)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,...,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,kinopoisk_url,mal_rating,mal_url,comments_count,reviews_count,url
3785,Паталлиро!,Boku | Boku Pataliro! | I Pataliro! | Patallir...,5895,вышел,Сериал,Весна 1982,PG-13,Сёдзё | Сёнэн-ай | Комедия | Приключения | Ром...,Манга,Toei Animation,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/1046527,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/patalliro
3718,Музик Тигр в лесу,Muzik Tiger | Muzik Tiger In the Forest | Музи...,12675,вышел,Малометражный сериал,Весна 2025,G,Повседневность,Оригинальная идея,Shin-Ei Animation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/muzik-tiger
3282,Семь смертных грехов: Спецвыпуски,Nanatsu no Taizai OVA | The Seven Deadly Sins:...,1315,вышел,OVA,Лето 2015,PG-13,Сёнэн | Приключения | Фэнтези | Экшен,Манга,A-1 Pictures,...,NaN,NaN,NaN,7.1,//kinopoisk.ru/film/1118056,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/sem-smert...
8085,"Небесный стрелок: Возвращение/Туда, куда дует ...",Gunslinger Stratos The Animation: Kikan/Kaze n...,11899,вышел,ONA,Лето 2015,PG-13,Фантастика | Экшен,Видеоигра,A-1 Pictures,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/nebesniy-...
2095,Несносные пришельцы 3: Помни мою любовь,Urusei Yatsura 3: Rimenbâ mai rabu | Urusei Ya...,7442,вышел,Полнометражный фильм,1985,PG-13,Сёнэн | Драма | Комедия | Приключения | Романт...,Манга,Studio Deen,...,NaN,NaN,NaN,NaN,//kinopoisk.ru/film/51671,NaN,NaN,NaN,NaN,https://old.yummyani.me/catalog/item/nesnosnye...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10142 entries, 0 to 10141
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_ru          10142 non-null  str
 1   alt_names         10140 non-null  str
 2   anime_id          10142 non-null  int64
 3   status            10142 non-null  str
 4   type              10142 non-null  str
 5   year              9897 non-null   str
 6   age_rating        10142 non-null  str
 7   genres            10109 non-null  str
 8   source            10142 non-null  str
 9   studio            9698 non-null   str
 10  director          8502 non-null   str
 11  dubbing           8360 non-null   str
 12  site_rating       10142 non-null  float64
 13  site_votes        10142 non-null  int64
 14  site_views        10142 non-null  str
 15  shikimori_rating  0 non-null      float64
 16  shikimori_url     0 non-null      float64
 17  worldart_rating   0 non-null      float64
 18  worldart_url      0 non-null      float64
 19  kinopoisk_rating  4209 non-null   float64
 20  kinopoisk_url     6959 non-null   str
 21  mal_rating        0 non-null      float64
 22  mal_url           0 non-null      float64
 23  comments_count    0 non-null      float64
 24  reviews_count     0 non-null      float64
 25  url               10142 non-null  str
dtypes: float64(10), int64(2), str(14)
memory usage: 2.0 MB

In [4]:
df.describe()

,anime_id,site_rating,site_votes,shikimori_rating,shikimori_url,worldart_rating,worldart_url,kinopoisk_rating,mal_rating,mal_url,comments_count,reviews_count
count,10142.000000,10142.000000,10142.000000,0.0,0.0,0.0,0.0,4209.000000,0.0,0.0,0.0,0.0
mean,9006.145139,6.414001,261.780319,NaN,NaN,NaN,NaN,6.982965,NaN,NaN,NaN,NaN
std,5790.678239,1.830632,686.914423,NaN,NaN,NaN,NaN,0.798113,NaN,NaN,NaN,NaN
min,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,3.400000,NaN,NaN,NaN,NaN
25%,5749.250000,5.840000,14.000000,NaN,NaN,NaN,NaN,6.400000,NaN,NaN,NaN,NaN
50%,8362.500000,6.760000,37.000000,NaN,NaN,NaN,NaN,6.900000,NaN,NaN,NaN,NaN
75%,11157.750000,7.520000,165.000000,NaN,NaN,NaN,NaN,7.600000,NaN,NaN,NaN,NaN
max,28053.000000,9.540000,9435.000000,NaN,NaN,NaN,NaN,9.100000,NaN,NaN,NaN,NaN

In [5]:
print('data types: ')
df.dtypes

data types:

title_ru                str
alt_names               str
anime_id              int64
status                  str
type                    str
year                    str
age_rating              str
genres                  str
source                  str
studio                  str
director                str
dubbing                 str
site_rating         float64
site_votes            int64
site_views              str
shikimori_rating    float64
shikimori_url       float64
worldart_rating     float64
worldart_url        float64
kinopoisk_rating    float64
kinopoisk_url           str
mal_rating          float64
mal_url             float64
comments_count      float64
reviews_count       float64
url                     str
dtype: object

In [6]:
print('num of rows and columns: ')
df.shape

num of rows and columns:

(10142, 26)

In [7]:
print('columns names: ')
df.columns

columns names:

Index(['title_ru', 'alt_names', 'anime_id', 'status', 'type', 'year',
       'age_rating', 'genres', 'source', 'studio', 'director', 'dubbing',
       'site_rating', 'site_votes', 'site_views', 'shikimori_rating',
       'shikimori_url', 'worldart_rating', 'worldart_url', 'kinopoisk_rating',
       'kinopoisk_url', 'mal_rating', 'mal_url', 'comments_count',
       'reviews_count', 'url'],
      dtype='str')

# 2. Missing Values

In [8]:
df.isnull().sum()

title_ru                0
alt_names               2
anime_id                0
status                  0
type                    0
year                  245
age_rating              0
genres                 33
source                  0
studio                444
director             1640
dubbing              1782
site_rating             0
site_votes              0
site_views              0
shikimori_rating    10142
shikimori_url       10142
worldart_rating     10142
worldart_url        10142
kinopoisk_rating     5933
kinopoisk_url        3183
mal_rating          10142
mal_url             10142
comments_count      10142
reviews_count       10142
url                     0
dtype: int64

In [9]:
#detecting missing values
missing = df.isnull().sum()
missing_pct = missing / df.shape[0] * 100
missing_above_20 = missing_pct[missing_pct > 20]

print('Columns with missing values > 20%:')
print('------------------------------------------------------------------------------------')
for col, pct in missing_above_20.items():
    print(f'{col}: {missing[col]} missing ({pct:.2f}%)')
print('------------------------------------------------------------------------------------')
print(f'Total columns affected: {len(missing_above_20)}')

Columns with missing values > 20%:
------------------------------------------------------------------------------------
shikimori_rating: 10142 missing (100.00%)
shikimori_url: 10142 missing (100.00%)
worldart_rating: 10142 missing (100.00%)
worldart_url: 10142 missing (100.00%)
kinopoisk_rating: 5933 missing (58.50%)
kinopoisk_url: 3183 missing (31.38%)
mal_rating: 10142 missing (100.00%)
mal_url: 10142 missing (100.00%)
comments_count: 10142 missing (100.00%)
reviews_count: 10142 missing (100.00%)
------------------------------------------------------------------------------------
Total columns affected: 10

In [10]:
#dropping empty columns
missing_100 = missing_pct[missing_pct == 100]

for col, pct in missing_100.items():
    df = df.drop(columns=col)
    print(f'{col} has been dropped because it has 100% missing values')

df.shape

shikimori_rating has been dropped because it has 100% missing values
shikimori_url has been dropped because it has 100% missing values
worldart_rating has been dropped because it has 100% missing values
worldart_url has been dropped because it has 100% missing values
mal_rating has been dropped because it has 100% missing values
mal_url has been dropped because it has 100% missing values
comments_count has been dropped because it has 100% missing values
reviews_count has been dropped because it has 100% missing values

(10142, 18)

In [ ]:
#column has only 2 miss, so filling it with empty string
df['alt_names'] = df['alt_names'].fillna('')

#filling missing values in 'year' column with median value
df['year'] = df['year'].str.extract('(\d{4})').astype(float)  # Extracting year as a 4-digit number and converting to float
df['year'] = df['year'].fillna(df['year'].median())
df['year'] = df['year'].astype(int)

#important column for our analysis, so filling missing values with 'Unknown'
df['genres'] = df['genres'].fillna('Unknown')



#filling missing values with median value
df['director'] = df['director'].fillna('Unknown')
df['dubbing'] = df['dubbing'].fillna('Unknown')
df['studio'] = df['studio'].fillna('Unknown')

#dropping columns that are not useful for our analysis and have many missing values
df = df.drop(columns=['kinopoisk_rating', 'kinopoisk_url'])

In [12]:
df.sample(25)

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
7800,Прибытие снежного короля,The Snow King Has Arrived | Xue Wang Jiadao | ...,11161,вышел,ONA,2023,PG-13,Приключения | Фэнтези | Не японское,Оригинальная идея,Nice Boat Animation,Unknown,FumoDub | Любительский одноголосый,5.50,8,3 642 просмотра,https://old.yummyani.me/catalog/item/pribytie-...
7427,Синий экзорцист: Вся ночь,Ao no Exorcist: Yosuga-hen | Blue Exorcist Sea...,13346,вышел,Сериал,2025,PG-13,Сёнэн | Фэнтези | Экшен,Манга,Studio VOLN,Ёсида Дайсукэ,AniLibria | Ados | Hekomi | Lupin | NastyhaGri...,8.62,470,159 300 просмотров,https://old.yummyani.me/catalog/item/ao-no-exo...
2013,О моём перерождении в слизь 2 | Часть 2,Tensei shitara Slime Datta Ken 2nd Season Part...,1015,вышел,Сериал,2021,PG-13,Сёнэн | Комедия | Приключения | Фэнтези | Демо...,Ранобэ,8bit,Накаяма Ацуси,AniDUB | Indominus Rex | Lonty | Lem0nka | Lon...,8.54,3489,445 878 просмотров,https://old.yummyani.me/catalog/item/o-moem-pe...
689,Практикуя ци сто тысяч лет,Lian Qi Shi Wan Nian | One Hundred Thousand Ye...,10212,онгоинг,ONA,2023,PG-13,Приключения | Фэнтези | Экшен | Боевые искусст...,Новелла,Soyep,Unknown,AniStar | Xelenum | Alice | AniMy | Любительск...,6.86,109,180 716 просмотров,https://old.yummyani.me/catalog/item/praktikuy...
3498,Именем игрока,Playbringer | Yi Wanjia Zhi Ming | В ім'я грав...,24843,анонс,ONA,2015,PG-13,Фэнтези | Экшен | Не японское | Китайское 3D,Оригинальная идея,Original Force,Unknown,Unknown,0.00,0,9 125 просмотров,https://old.yummyani.me/catalog/item/yi-wanjia...
6373,Ван-Пис: Остров Рыболюдей,One Piece Log: Fish-Man Island Saga | ONE PIEC...,15421,вышел,Сериал,2024,PG-13,Сёнэн | Приключения | Фэнтези | Экшен,Манга,Toei Animation,Нагаминэ Тацуя,Crunchyroll | AniDUB | AniDub Online | AniMaun...,7.67,108,55 810 просмотров,https://old.yummyani.me/catalog/item/van-pis-o...
7269,Восход с нуля,Zero Rise | Схід із нуля | ゼロライズ,26152,анонс,Сериал,2015,Неизвестно,Спорт,Мультимедийный проект,Nichicaline,Unknown,Unknown,0.00,0,6 489 просмотров,https://old.yummyani.me/catalog/item/zero-rise
6012,Извивающийся дракон,"Coiling Dragon | Panlong | Дракон, що звиваєть...",27850,анонс,ONA,2026,PG-13,Приключения | Фэнтези | Экшен | Не японское | ...,Визуальная новелла,CG Year,Unknown,Unknown,0.00,0,2 966 просмотров,https://old.yummyani.me/catalog/item/izvivayus...
2303,Покемон: Путешествие Эша,Ash's Journey | Pokemon Introductory Recap | P...,11626,вышел,Короткометражный фильм,1998,PG,Сёнэн | Комедия | Приключения | Фэнтези,Игра,Oriental Light & Magic,Unknown,Unknown,5.53,34,11 399 просмотров,https://old.yummyani.me/catalog/item/pokemon-f...
6240,Кураюкаба,Kurayukaba | クラユカバ,11822,вышел,Полнометражный фильм,2024,PG-13,Детектив | Триллер | Фантастика,Оригинальная идея,Team OneOne,Цукахара Сигэёси,AniBaza | Pandora | Abe | Nate | RusDubber | A...,7.12,50,21 914 просмотров,https://old.yummyani.me/catalog/item/kurayukaba
9305,Девушка на час 5,"Kanojo, Okarishimasu 5th Season | Kanokari | R...",23365,онгоинг,Сериал,2026,PG-13,Сёнэн | Комедия | Романтика | Гарем,Манга,TMS Entertainment,Кога Кадзуоми,Crunchyroll | Amazing Dubbing | AniBaza | AniD...,4.58,229,162 902 просмотра,https://old.yummyani.me/catalog/item/kanojo-ok...
6610,Можете ли вы постирать это ради меня?,Kirei ni Shitemoraemasu ka. | Wash It All Away...,21152,вышел,Сериал,2026,PG-13,Сэйнэн | Повседневность,Манга,Okuruto Noboru,Ониси Кэнта,Crunchyroll | AniDUB | AniStar | AnimeVost | K...,7.26,183,125 937 просмотров,https://old.yummyani.me/catalog/item/mozhete-l...
219,Дракон Раджа 3,Dragon Raja 3rd Season | Dragon Raja III: Blac...,25888,анонс,ONA,2028,PG-13,Приключения | Фэнтези | Суперспособности | Не ...,Новелла,Garden Culture,Unknown,Unknown,0.00,0,36 381 просмотр,https://old.yummyani.me/catalog/item/long-zu-i...
95,Сломанный меч 6: Цитадель скорби,Break Blade 6: Enclave of Lamentations | Break...,7849,вышел,Полнометражный фильм,2011,R-17+,Сёнэн | Меха | Приключения | Фэнтези | Экшен |...,Манга,Production I.G | Xebec,Амино Тэцуро | Хабара Нобуёси,AniDUB | AniFilm | AniPLague | Cuba77,7.88,99,18 365 просмотров,https://old.yummyani.me/catalog/item/slomannyy...
7040,Инфинити Надо 3,Infinity Nado 3 | Zhandou Wang Zhi Jufeng Zhan...,11177,вышел,Сериал,2015,PG,Экшен | Не японское,Оригинальная идея,Alpha Animation,Unknown,Straight.Pro,6.55,11,4 593 просмотра,https://old.yummyani.me/catalog/item/infiniti-...
4690,Эта девушка милая... но опасная?,"Are You a Jirai Girl, Chihara-san? | Jirai nan...",25740,анонс,Сериал,2026,Неизвестно,Комедия | Романтика,Манга,SynergySP,Фудзии Ясуаки,Unknown,0.00,0,26 983 просмотра,https://old.yummyani.me/catalog/item/eta-devus...
1291,Великий из бродячих псов 2,Bungo Stray Dogs | Bungo Stray Dogs 2 | Bungou...,1563,вышел,Сериал,2016,R-17+,Сэйнэн | Детектив | Приключения | Экшен | Супе...,Манга,Bones,Игараси Такуя,Студийная банда AD | Jam | Cuba77 | Давид Петр...,8.13,1701,183 091 просмотр,https://old.yummyani.me/catalog/item/velikij-i...
4993,История Мерк,Merc Storia: Mukiryoku no Shounen to Bin no Na...,5533,вышел,Сериал,2018,PG-13,Приключения | Фэнтези | Экшен,Игра,Encourage Films,Оидзаки Фумитоси,AniLibria | Anzen | MyAska | AniDUB | AniMedia,7.04,89,17 983 просмотра,https://old.yummyani.me/catalog/item/istoriya-...
8974,Расколотая битвой синева небес,Battle Through the Heavens | Dou po cang qiong...,5343,вышел,ONA,2017,PG-13,Комедия | Приключения | Романтика | Фэнтези | ...,Новелла,Foch Films,Unknown,AniDUB | Cuba77 | Esther | SoftBox | Студия Ко...,7.14,195,80 345 просмотров,https://old.yummyani.me/catalog/item/raskolota...
331,Террорист,Terror Man | Терорист | 테러맨,24337,вышел,ONA,2026,PG-13,Экшен | Не японское | Сверхъестественное,Манхва,DR Movie,Unknown,ТО Дубляжная | Виктор Андреев | Андрей Сазонов...,7.63,649,466 594 просмотра,https://old.yummyani.me/catalog/item/terrorist
6787,Достичь Терры,Chikyuu he | Terra e... | Terra e... (2007) | ...,9702,вышел,Сериал,2007,PG-13,Сёнэн | Драма | Фантастика | Космос | Экшен | ...,Манга,Tokyo Kids | Minami Machi Bugyousho,Ямасаки Осаму,SHIZA Project,7.59,32,11 178 просмотров,https://old.yummyani.me/catalog/item/dostich-t...
9755,Люпен III: Замок Калиостро,Lupin III: Cagliostro no Shiro | Lupin III: Th...,716,вышел,Полнометражный фильм,1979,PG-13,Сэйнэн | Детектив | Комедия | Приключения | Фа...,Манга,TMS,Миядзаки Хаяо,СВ-Дубль | СВ Студия,8.39,122,26 728 просмотров,https://old.yummyani.me/catalog/item/lyupen-ii...
5239,Рандеву с жизнью F: Последнее свидание,Date A Live F: Last Date | デート・ア・ライブF Last Dat,27900,анонс,Неизвестно,2015,R-17+,Сёнэн | Романтика | Фантастика | Фэнтези | Экш...,Ранобэ,Fugaku,Нисимура Дзюндзи,Unknown,0.00,0,3 444 просмотра,https://old.yummyani.me/catalog/item/randevu-z...
8168,Секс-коммандо: Масару - это круто!,Sexy Commando Gaiden: Sugoi yo!! Masaru-san | ...,7355,вышел,Малометражный сериал,1998,R-17+,Сёнэн | Комедия | Боевые искусства | Школьная ...,Манга,Magic Bus,Сатоси Дэдзаки,Unknown,5.83,12,11 522 просмотра,https://old.yummyani.me/catalog/item/seks-komm...
3958,Неистовый танец мечей,Katsugeki Touken Ranbu | Katsugeki/Touken Ranb...,9717,вышел,Сериал,2017,PG-13,Фэнтези | Экшен | Самураи | Исторический,Игра,ufotable,Сирай Тосиюки,AniLibria | KANSAI Studio,6.71,41,22 735 просмотров,https://old.yummyani.me/catalog/item/tanec-mechey

# 3. Data Types & Format Issues

In [13]:
print(df.dtypes)

title_ru           str
alt_names          str
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres             str
source             str
studio             str
director           str
dubbing            str
site_rating    float64
site_votes       int64
site_views         str
url                str
dtype: object

In [ ]:
#converting columns to numeric
df['site_views'] = df['site_views'].str.extract('(\d+)').astype(int)
df['site_views']

0         6
1         6
2         6
3         4
4        10
         ..
10137    36
10138    28
10139     7
10140    10
10141     9
Name: site_views, Length: 10142, dtype: int64

In [16]:
#splitting columns with multiple values into lists
df['genres'] = df['genres'].str.split('|')
df['alt_names'] = df['alt_names'].str.split('|')
df['studio'] = df['studio'].str.split('|')
df['director'] = df['director'].str.split('|')
df['dubbing'] = df['dubbing'].str.split('|')

In [17]:
df

,title_ru,alt_names,anime_id,status,type,year,age_rating,genres,source,studio,director,dubbing,site_rating,site_votes,site_views,url
0,Моя история продолжается сегодня,"[Kyou, Watashi no Monogatari ga Hashirimasu. ,...",10800,вышел,ONA,2023,G,"[Повседневность , Спорт]",Оригинальная идея,[Studio Colorido],[Синго Ямасита],[AniLane],6.74,19,6,https://old.yummyani.me/catalog/item/moya-isto...
1,Детектив Конан: Цель — Когоро! Секретное рассл...,[Detective Conan OVA 05: The Target is Kogoro!...,8258,вышел,OVA,2005,PG-13,"[Сёнэн , Детектив , Комедия , Приключения ,...",Манга,[TMS Entertainment],[Сато Масато],[Persona99],6.65,23,6,https://old.yummyani.me/catalog/item/detektiv-...
2,Сердце дракона: Хроника исследования мира духов,"[Dragon Heart: Adventures Beyond This World , ...",18742,вышел,Полнометражный фильм,2025,G,"[Фэнтези , Драконы , Сверхъестественное]",Оригинальная идея,[HS Pictures Studio],[Имакакэ Исаму],[Unknown],5.60,5,6,https://old.yummyani.me/catalog/item/dragon-he...
3,Госпожа Кэйфуку,"[Keifuku-san , Keifukusan , Пані Кейфуку , ...",6905,вышел,ONA,2017,G,[Фэнтези],Оригинальная идея,[Yaoyorozu],[Тацуки],"[Panzu.info , ХЗ Лол]",5.28,18,4,https://old.yummyani.me/catalog/item/gospozha-...
4,Ветер из Лояна: Таинственный мальчик,"[Feng qi luo yang zhi shen ji shao nian , Fen...",6198,вышел,ONA,2021,PG-13,"[Детектив , Приключения , Фэнтези , Экшен ,...",Оригинальная идея,[Chosen],[Unknown],"[AniStar , Автоперевод , ПВА ШОУ]",6.42,19,10,https://old.yummyani.me/catalog/item/veter-iz-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,Проект Кей: Возвращение королей,"[K , K 2nd Season , K RETURN OF KINGS , K-P...",7262,вышел,Сериал,2015,PG-13,"[Фэнтези , Экшен , Суперспособности]",Оригинальная идея,[GoHands],"[Судзуки Синго , Канадзава Хиромити]","[AniDUB , AniLibria , Onibaku , SHIZA Project]",7.79,323,36,https://old.yummyani.me/catalog/item/proekt-ke...
10138,Великий блюз!,"[Grablu! , Grand Blues! , Guraburu! , Грабл...",1561,вышел,Малометражный сериал,2020,PG-13,"[Приключения , Фэнтези]",Манга,"[W-Toon Studio , DMM.futureworks]",[Мории Кэнсиро],"[AniLibria , Hoopoe , Renie , Frederica Izz...",5.23,30,28,https://old.yummyani.me/catalog/item/velikij-b...
10139,Мэйз: Пространство мегавзрыва,"[Maze bakunetsu jikû , Maze: The Mega-Burst S...",6910,вышел,Сериал,1997,PG-13,"[Сёнэн , Комедия , Меха , Пилотируемые робо...",Ранобэ,[J.C.Staff],[Судзуки Ику],"[Animegroup , Get Smart Group , Persona99]",5.73,15,7,https://old.yummyani.me/catalog/item/meyz-pros...
10140,Нарутару,"[Narutaru: Mukuro naru hoshi tama taru ko , S...",9458,вышел,Сериал,2003,R-17+,"[Сэйнэн , Драма , Триллер , Фэнтези]",Манга,[Planet],[Иино Тосиаки],[AniDUB],6.13,23,10,https://old.yummyani.me/catalog/item/narutaru
10141,Человеческие отношения,"[Homeroom Affairs , Human Relations , Tanin ...",7178,вышел,OVA,1994,R+,"[Этти , Комедия , Романтика , Школьная жизнь]",Манга,[J.C.Staff],[Сэкита Осаму],[Unknown],5.95,22,9,https://old.yummyani.me/catalog/item/chelovech...

# 4. Duplicate Data

In [ ]:
#checking and resolving duplicate anime_id
dup_ids = df[df['anime_id'].duplicated(keep=False)]
print(f"Rows with duplicate anime_id: {len(dup_ids)}")

#keeping only the first occurrence
df = df.drop_duplicates(subset='anime_id', keep='first')
print(f"Shape after deduplication: {df.shape}")

Rows with duplicate anime_id: 0
Shape after deduplication: (10142, 17)

# 5. Invalid or Suspicious Values

In [ ]:
#manually checking for issues in the data
issues = {}

issues['year_out_of_range'] = df[(df['year'] < 1900) | (df['year'] > 2030)]
issues['rating_out_of_range'] = df[(df['site_rating'] < 0) | (df['site_rating'] > 10)]
issues['votes_negative'] = df[df['site_votes'] < 0]
issues['views_negative'] = df[df['site_views'] < 0]
issues['duplicate_anime_id'] = df[df['anime_id'].duplicated(keep=False)]
issues['empty_title'] = df[df['title_ru'].isna()]
issues['empty_type'] = df[df['type'].isna()]
issues['empty_status'] = df[df['status'].isna()]
issues['empty_genres'] = df[df['genres'].isna()]

In [19]:
issues

{'year_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'rating_out_of_range': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'votes_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'views_negative': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'duplicate_anime_id': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_title': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_type': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_status': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: [],
 'empty_genres': Empty DataFrame
 Columns: [title_ru, alt_names, anime_id, status, type, year, age_rating, genres, source, studio, director, dubbing, site_rating, site_votes, site_views, url]
 Index: []}

In [26]:
num_cols = ['year', 'site_rating', 'site_votes', 'site_views']


#z-score method
z_scores = (df[num_cols] - df[num_cols].mean()) / df[num_cols].std()
z_outliers = np.abs(z_scores) > 3

#iqr method
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

iqr_outliers = (df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR))

#merging outliers from both methods
outliers = z_outliers | iqr_outliers

#rows with issues
df_outliers = df[outliers.any(axis=1)]

#marking
df['suspicious'] = outliers.any(axis=1)

#checking
df_outliers[num_cols].sample(50)

       year  site_rating  site_votes  site_views
2650   2006         8.16         852         158
9741   2012         7.27         421          93
2290   1983         6.73          11           8
5223   2024         8.69         314          89
5096   2018         7.82        1103         247
1730   2022         7.15         741         170
6332   2017         8.79         523          41
5819   2014         8.39         832         206
8165   2027         0.00           0           6
10118  2012         8.66        7179           1
2205   2023         8.42        3904         764
1982   2019         8.25         484         102
7308   2024         7.36         827         199
1363   2025         7.92         578         293
2226   2017         7.94         683          80
3042   1975         6.63          30           8
971    2017         7.80         544          51
7729   2024         8.70        1324         941
2685   2027         0.00           0           1
9098   2026         0.00           0          10
3184   2015         0.00           0           4
9742   2024         8.21         463         350
7402   2017         7.65        1006          70
2793   2022         8.16         751          70
2124   2024         7.23        1753         426
6276   1970         9.05         244         315
2131   2023         8.64        1049         134
1611   2026         9.20        2739           2
1340   2012         7.58         677          57
7268   2025         6.92        2147         895
4263   2024         6.38         638         204
9852   2010         7.15         439          39
2973   2025         8.28          50         135
6509   2024         8.35        1947         612
344    1983         6.10          10           5
6917   2017         7.89         535          52
3984   2025         6.70         493         346
2980   1984         6.18          17           7
7346   2022         8.29        2880         366
6963   2027         0.00           0          18
5767   1981         4.75           4           4
1237   2019         7.27         283         110
9084   2015         7.34         892          40
8716   2019         7.34         253         135
5181   1979         7.33           9           6
3733   2025         7.80         339         359
3307   2025         0.00           0           5
8043   2023         7.50        1234         216
7830   2026         7.32         437         343
9669   1962         5.69          16           5

We examined the outliers and suspicious values, but concluded that in this case they cannot be analyzed reliably due to the very high variance. We also believe these values are valid, as such data can realistically occur. Therefore, we decided not to remove these outliers

In [28]:
# final validation
print("Final shape")
print(df.shape)

print("Remaining missing values")
print(df.isnull().sum())

print("Data types")
print(df.dtypes)

Final shape
(10142, 17)
Remaining missing values
title_ru       0
alt_names      0
anime_id       0
status         0
type           0
year           0
age_rating     0
genres         0
source         0
studio         0
director       0
dubbing        0
site_rating    0
site_votes     0
site_views     0
url            0
suspicious     0
dtype: int64
Data types
title_ru           str
alt_names       object
anime_id         int64
status             str
type               str
year             int64
age_rating         str
genres          object
source             str
studio          object
director        object
dubbing         object
site_rating    float64
site_votes       int64
site_views       int64
url                str
suspicious        bool
dtype: object